version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      # Use absolute path for better performance
      - ${PWD}:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - storeall-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ${PWD}:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - storeall-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: storeall_dev
      MYSQL_USER: storeall_user
      MYSQL_PASSWORD: storeall_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - storeall-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - storeall-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - storeall-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - storeall-network

volumes:
  mysql_data:

networks:
  storeall-network:
    driver: bridge

